[project]
name = "photocipher-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
    "cryptography>=46.0.3",
    "platformdirs>=4.5.1",
]

[project.scripts]
photocipher = "photocipher.main:main"

